var sadi = 3;
var naimur = 4;
var tem = 0;
tem = sadi;
sadi = naimur;
naimur = tem;
console.log(sadi, naimur);
var a = 1 , b = 2;
a = a + b;
b = a - b;
a = a - b;
console.log (a,b);
var c = 5, d = 6;
[c,d] =[d,c];
console.log(c,d);